#!/usr/bin/env python
import os
import sys
import textwrap

if len(sys.argv) < 3:
    print("Usage: odpsub [pattern] [inputfile]")
    print(f"sys argv was: {sys.argv}")
    exit(0)

if "output" not in os.listdir('.'):
    os.system("mkdir output")

patt = sys.argv[1]
input_file = sys.argv[2]
full_fn = input_file[input_file.rindex('/')+1:]
filename = full_fn[:full_fn.rindex('.')]
ext = full_fn[full_fn.rindex('.')+1:]

print(f"target: {patt}")
fmt_cmd = f"mkdir output/{filename}; cat {input_file} | ./prep_onto >./output/{filename}/{filename}.formatted.{ext}"
print(fmt_cmd)
os.system(fmt_cmd)

sub_cmd = textwrap.dedent(
    f"""
    cat ./output/{filename}/{filename}.formatted.{ext} \\
    | ./bin/find_{patt}_instances | tee ./output/{filename}/{filename}.{patt}.instances \\
    | ./make_subs.py {patt} 2>./output/{filename}/{filename}.{patt}.make_subs.log | tee ./output/{filename}/{filename}.{patt}.subs \\
    | ./sub_patt.py ./output/{filename}/{filename}.formatted.{ext} > ./output/{filename}/{filename}.sub_{patt}.{ext}
    """).strip()
print(sub_cmd)
os.system(sub_cmd)
